### ISSUE TITLE
What am I supposed to name the config file?

### ISSUE THREAD

**Issue by Evilwigi** [mmatyas/supermariowar#184] opened 2021-03-17 01:20 UTC
I have no idea what i'm supposed to name the thing. No matter what I do the server program doesn't recognize it.

**Comment by mmatyas** [comment] 2021-03-17 17:30
Hi I've just added some documentation here: https://github.com/mmatyas/supermariowar/blob/master/docs/netplay.md

**Comment by Evilwigi** [comment] 2021-03-17 18:24
I have tried following that but the smw-server program still won't recognize it.

**Comment by mmatyas** [comment] 2021-03-17 18:28
Hm, how are you launching the program (eg. command line, shortcut)? What is the error you see on the log?

**Comment by Evilwigi** [comment] 2021-03-17 18:32
I'm just clicking on the smw-server program and it just shows this:

SMW Server alpha
[warning] Configuration file not found, using default values.
  server name: SMW Server
  max players: 20
Ready!

**Comment by mmatyas** [comment] 2021-04-03 22:12
Just pushed an update, the server will now tell the file it tries to load, and you can also load a custom one by giving its path as a command line parameter (eg. through a shortcut or by command prompt launching).

**Comment by mmatyas** [comment] 2021-10-04 14:40
Just a small update, the file can be named `serverconfig.txt` too now, in case the issue is related to the file extension, which may be hidden on Windows. I'm closing this issue for now, but if there's still some issues, feel free to report it!

**Closed by mmatyas** 2021-10-04 14:40 UTC
